networks:
    backend:
        driver: bridge

services:
    gateway:
        build:
            context: ./gateway
            dockerfile: Dockerfile
        container_name: gateway
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - '${GATEWAY_PORT}:${GATEWAY_PORT}'
        networks:
            - backend
        depends_on:
            - auth
            - event
    auth:
        build:
            context: ./auth
            dockerfile: Dockerfile
        container_name: auth
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - '${AUTH_PORT}:${AUTH_PORT}'
        networks:
            - backend
        depends_on:
            - mongo-auth
    event:
        build:
            context: ./event
            dockerfile: Dockerfile
        container_name: event
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - '${EVENT_PORT}:${EVENT_PORT}'
        networks:
            - backend
        depends_on:
            - mongo-event
    mongo-auth:
        image: mongo:latest
        container_name: mongo-auth
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_AUTH_NAME}
        volumes:
            - mongo_auth_data:/data/db
        ports:
            - '${MONGO_AUTH_PORT}:27017'
        networks:
            - backend
    mongo-event:
        image: mongo:latest
        container_name: mongo-event
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_EVENT_NAME}
        volumes:
            - mongo_event_data:/data/db
        ports:
            - '${MONGO_EVENT_PORT}:27017'
        networks:
            - backend
volumes:
    mongo_auth_data:
    mongo_event_data:
